// Copyright 2026 Kelvin Cushman and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package cli

import (
	"fmt"
	"os"
	"os/exec"
	"runtime"
	"strings"

	"github.com/spf13/cobra"
	"kie-pp-cli/internal/cliutil"
	"kie-pp-cli/internal/config"
)

func newAuthCmd(flags *rootFlags) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "auth",
		Short: "Manage authentication for Kie Ai",
		RunE:  parentNoSubcommandRunE(flags),
	}

	cmd.AddCommand(newAuthSetupCmd(flags))
	cmd.AddCommand(newAuthStatusCmd(flags))
	cmd.AddCommand(newAuthLogoutCmd(flags))

	return cmd
}

// newAuthSetupCmd starts the interactive, credential-safe first-run setup. It
// prints non-blocking directions instead when stdout or stdin is not a terminal.
func newAuthSetupCmd(flags *rootFlags) *cobra.Command {
	var launch bool
	cmd := &cobra.Command{
		Use:     "setup",
		Short:   "Guided API key setup",
		Example: "  kie-pp-cli auth setup\n  kie-pp-cli auth setup --launch",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runAuthSetup(cmd, flags, launch, nil)
		},
	}
	cmd.Flags().BoolVar(&launch, "launch", false, "Open the Get API key page in your default browser")
	return cmd
}

// runAuthSetup uses readKey only in tests. Production calls readMaskedAPIKey,
// which disables terminal echo before it reads the key.
func runAuthSetup(cmd *cobra.Command, flags *rootFlags, launch bool, readKey func(*cobra.Command) (string, error)) error {
	if !canGuideAuthSetup(cmd, flags) && readKey == nil {
		return printAuthSetupHint(cmd, flags)
	}

	w := cmd.OutOrStdout()
	fmt.Fprintln(w, "Kie API key setup")
	fmt.Fprintf(w, "Get Kie.ai API access and support continued development: %s\n", cliutil.KieAPIKeyURL)
	fmt.Fprintln(w, cliutil.KieAffiliateDisclosure)
	fmt.Fprintln(w, "Your key is entered hidden and is never placed in shell history.")
	if launch {
		if err := openSetupURL(cliutil.KieAPIKeyURL); err != nil {
			fmt.Fprintf(cmd.ErrOrStderr(), "could not open browser automatically: %v\nOpen this URL manually: %s\n", err, cliutil.KieAPIKeyURL)
		}
	}

	if readKey == nil {
		readKey = readMaskedAPIKey
	}
	key, err := readKey(cmd)
	if err != nil {
		return configErr(fmt.Errorf("reading API key: %w", err))
	}
	key = strings.TrimSpace(key)
	if key == "" {
		return usageErr(fmt.Errorf("API key cannot be empty"))
	}

	cfg, err := config.Load(flags.configPath)
	if err != nil {
		return configErr(err)
	}
	if err := saveAuthToken(cfg, key); err != nil {
		return configErr(fmt.Errorf("saving API key: %w", err))
	}
	fmt.Fprintf(w, "API key saved securely to %s\n", credentialSavePath(cfg))
	fmt.Fprintln(w, "Run 'kie-pp-cli doctor --json' to check your setup.")
	return nil
}

func canGuideAuthSetup(cmd *cobra.Command, flags *rootFlags) bool {
	in, inputIsFile := cmd.InOrStdin().(*os.File)
	return !cliutil.IsVerifyEnv() &&
		!flags.noInput && !flags.agent && !flags.asJSON && !flags.csv && !flags.plain && !flags.quiet && !flags.dryRun && !flags.yes &&
		inputIsFile && isTerminal(in) && isTerminal(cmd.OutOrStdout())
}

func printAuthSetupHint(cmd *cobra.Command, flags *rootFlags) error {
	if flags.asJSON || flags.agent {
		return printJSONFiltered(cmd.OutOrStdout(), map[string]any{
			"setup_required":        true,
			"next_step":             "kie-pp-cli auth setup",
			"get_api_key":           cliutil.KieAPIKeyURL,
			"get_api_key_link_type": "affiliate",
			"affiliate_disclosure":  cliutil.KieAffiliateDisclosure,
		}, flags)
	}
	if flags.csv {
		_, err := fmt.Fprintln(cmd.OutOrStdout(), "setup_required,next_step\ntrue,kie-pp-cli auth setup")
		return err
	}
	if flags.plain || flags.quiet {
		_, err := fmt.Fprintln(cmd.OutOrStdout(), "kie-pp-cli auth setup")
		return err
	}
	fmt.Fprintln(cmd.OutOrStdout(), "Get Kie.ai API access and support continued development:", cliutil.KieAPIKeyURL)
	fmt.Fprintln(cmd.OutOrStdout(), cliutil.KieAffiliateDisclosure)
	fmt.Fprintln(cmd.OutOrStdout(), "Run 'kie-pp-cli auth setup' in an interactive terminal to enter and save your key securely.")
	return nil
}

func readMaskedAPIKey(cmd *cobra.Command) (string, error) {
	in, ok := cmd.InOrStdin().(*os.File)
	if !ok {
		return "", fmt.Errorf("standard input is not a terminal")
	}
	fmt.Fprint(cmd.OutOrStdout(), "API key (input hidden): ")
	key, err := readMaskedTerminalLine(in)
	fmt.Fprintln(cmd.OutOrStdout())
	return key, err
}

// openSetupURL opens url in the OS default browser. Per the side-effect rule,
// the caller short-circuits with cliutil.IsVerifyEnv() before this is reached.
func openSetupURL(url string) error {
	var c *exec.Cmd
	switch runtime.GOOS {
	case "darwin":
		c = exec.Command("open", url)
	case "linux":
		c = exec.Command("xdg-open", url)
	case "windows":
		c = exec.Command("rundll32", "url.dll,FileProtocolHandler", url)
	default:
		return fmt.Errorf("unsupported OS: %s", runtime.GOOS)
	}
	return c.Start()
}

func newAuthStatusCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "status",
		Short:   "Show authentication status",
		Example: "  kie-pp-cli auth status",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			w := cmd.OutOrStdout()
			header := cfg.AuthHeader()
			authed := header != ""
			// JSON envelope: {authenticated, verified, source, config}. When not
			// authenticated, write the envelope first then return authErr
			// so exit code carries the auth-failure signal.
			if flags.asJSON {
				out := map[string]any{
					"authenticated": authed,
					"verified":      false,
					"source":        cfg.AuthSource,
					"config":        cfg.Path,
				}
				if printErr := printJSONFiltered(w, out, flags); printErr != nil {
					return printErr
				}
				if !authed {
					return authErr(fmt.Errorf("no credentials configured"))
				}
				return nil
			}
			if !authed {
				fmt.Fprintln(w, red("Not authenticated"))
				fmt.Fprintln(w, "")
				fmt.Fprintln(w, "Run 'kie-pp-cli auth setup' in an interactive terminal to save your API key securely.")
				fmt.Fprintln(w, "For scripts and CI, set KIE_BEARER_AUTH through that environment's secret store.")
				return authErr(fmt.Errorf("no credentials configured"))
			}

			fmt.Fprintln(w, green("Credentials present (not verified)"))
			fmt.Fprintf(w, "  Source: %s\n", cfg.AuthSource)
			fmt.Fprintf(w, "  Config: %s\n", cfg.Path)
			return nil
		},
	}
}

// saveAuthToken is shared by the hidden-input wizard and its tests so both use
// the existing private credential store.
func saveAuthToken(cfg *config.Config, token string) error {
	// Clear any legacy auth_header so AuthHeader() falls through to the saved
	// credential. Keep this silent: output must never reveal token bytes.
	cfg.AuthHeaderVal = ""
	return cfg.SaveTokens("", "", token, "", cfg.TokenExpiry)
}

func credentialSavePath(cfg *config.Config) string {
	if cfg != nil && cfg.AgentcookieManagedByExternalStore() {
		return cfg.Path
	}
	if path, err := cliutil.CredentialsFilePath(); err == nil {
		return path
	}
	if cfg != nil {
		return cfg.Path
	}
	return ""
}

func newAuthLogoutCmd(flags *rootFlags) *cobra.Command {
	return &cobra.Command{
		Use:     "logout",
		Short:   "Clear stored credentials",
		Example: "  kie-pp-cli auth logout",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg, err := config.Load(flags.configPath)
			if err != nil {
				return configErr(err)
			}

			if err := cfg.ClearTokens(); err != nil {
				return configErr(fmt.Errorf("clearing tokens: %w", err))
			}

			// Identify which (if any) auth env var is still exported so the
			// JSON envelope and the human prose can both surface it.
			envStillSet := ""
			if envStillSet == "" && os.Getenv("KIE_BEARER_AUTH") != "" {
				envStillSet = "KIE_BEARER_AUTH"
			}

			// JSON envelope: {cleared: true, note?: "<env_var> env var is still set"}.
			if flags.asJSON {
				out := map[string]any{"cleared": true}
				if envStillSet != "" {
					out["note"] = envStillSet + " env var is still set"
				}
				return printJSONFiltered(cmd.OutOrStdout(), out, flags)
			}

			if envStillSet != "" {
				fmt.Fprintf(cmd.OutOrStdout(), "Config cleared. Note: %s env var is still set.\n", envStillSet)
				return nil
			}
			fmt.Fprintln(cmd.OutOrStdout(), "Logged out. Credentials cleared.")
			return nil
		},
	}
}
