#!/usr/bin/env bash
# Rebuild every current Kie.ai API/model contract and regenerate the printed
# CLI without ever asking Printing Press to recreate the live Git worktree.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON_BIN="${PYTHON_BIN:-python3}"
PRINTING_PRESS_BIN="${PRINTING_PRESS_BIN:-cli-printing-press}"
cd "$REPO_DIR"

command -v "$PYTHON_BIN" >/dev/null || { echo "missing Python: $PYTHON_BIN" >&2; exit 1; }
command -v "$PRINTING_PRESS_BIN" >/dev/null || {
  echo "missing CLI Printing Press; install github.com/mvanhorn/cli-printing-press/v4/cmd/cli-printing-press@v4.30.1" >&2
  exit 1
}
command -v rsync >/dev/null || { echo "missing required command: rsync" >&2; exit 1; }

"$PYTHON_BIN" research/build_spec.py
"$PYTHON_BIN" research/build_academy_map.py --preserve-generated-at-if-unchanged
"$PYTHON_BIN" research/refresh_model_leaderboard.py --preserve-generated-at-if-unchanged

# --force recreates its output directory. Run it only against a disposable
# mirror; pointing it at the live checkout would remove .git and hand-authored
# files before its AST preservation pass. The mirror contains the current
# patched generated files so Printing Press can merge those patches forward.
TEMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/kie-cli-refresh.XXXXXX")"
PRESERVED_DIR="$TEMP_ROOT/preserved"
PRISTINE_DIR="$TEMP_ROOT/pristine"
cleanup() { rm -rf "$TEMP_ROOT"; }
trap cleanup EXIT
mkdir -p "$PRESERVED_DIR"
rsync -a --exclude=.git --exclude=bin --exclude=build "$REPO_DIR/" "$PRESERVED_DIR/"

"$PRINTING_PRESS_BIN" generate \
  --spec "$PRESERVED_DIR/research/kie-final-openapi.yaml" \
  --name kie \
  --spec-source docs \
  --output "$PRESERVED_DIR" \
  --force \
  --validate=false
"$PYTHON_BIN" research/patch_generated_cli.py --root "$PRESERVED_DIR" --preserved

# AST preservation intentionally keeps hand-authored framework extensions, but
# it also keeps old endpoint functions. Print a second, pristine tree so every
# current endpoint flag and body field is sourced from today's merged spec.
"$PRINTING_PRESS_BIN" generate \
  --spec "$REPO_DIR/research/kie-final-openapi.yaml" \
  --name kie \
  --spec-source docs \
  --output "$PRISTINE_DIR" \
  --validate=false
"$PYTHON_BIN" research/patch_generated_cli.py --root "$PRISTINE_DIR"

sync_generated_go_dir() {
  local relative_dir="$1"
  local source_dir="$PRESERVED_DIR/$relative_dir"
  local target_dir="$REPO_DIR/$relative_dir"
  mkdir -p "$target_dir"

  while IFS= read -r source; do
    local name
    name="$(basename "$source")"
    if grep -q "Generated by CLI Printing Press" "$source"; then
      cp "$source" "$target_dir/$name"
    fi
  done < <(find "$source_dir" -maxdepth 1 -type f -name '*.go' | sort)

  while IFS= read -r target; do
    local name
    name="$(basename "$target")"
    if grep -q "Generated by CLI Printing Press" "$target" && [[ ! -f "$source_dir/$name" ]]; then
      rm "$target"
    fi
  done < <(find "$target_dir" -maxdepth 1 -type f -name '*.go' | sort)
}

sync_generated_go_dir internal/cli
sync_generated_go_dir internal/mcp
sync_generated_go_dir internal/types
cp "$PRESERVED_DIR/spec.yaml" "$REPO_DIR/spec.yaml"
cp "$PRESERVED_DIR/tools-manifest.json" "$REPO_DIR/tools-manifest.json"

# Endpoint commands are safe to replace wholesale: local behavior lives in
# non-generated decorators, except for the compatibility patches reapplied
# above. This prevents AST preservation from hiding newly documented fields.
while IFS= read -r source; do
  if grep -q '"pp:endpoint"' "$source"; then
    cp "$source" "$REPO_DIR/internal/cli/$(basename "$source")"
  fi
done < <(find "$PRISTINE_DIR/internal/cli" -maxdepth 1 -type f -name '*.go' | sort)

while IFS= read -r target; do
  name="$(basename "$target")"
  if grep -q '"pp:endpoint"' "$target" && [[ ! -f "$PRISTINE_DIR/internal/cli/$name" ]]; then
    rm "$target"
  fi
done < <(find "$REPO_DIR/internal/cli" -maxdepth 1 -type f -name '*.go' | sort)

# Verify the synchronized live tree as well. This catches any Printing Press
# preservation behavior that changes which copy of a framework file wins.
"$PYTHON_BIN" research/patch_generated_cli.py --root "$REPO_DIR" --preserved

# Make the official index the final authority for docs, registry, coverage,
# and the spec checksum after the generated Go files are synchronized.
cd "$REPO_DIR"
"$PYTHON_BIN" research/build_spec.py

gofmt -w cmd internal/academy internal/cli internal/kiecatalog internal/leaderboard internal/mcp internal/media internal/mediamcp internal/types
"$PYTHON_BIN" -m unittest discover -s research -p 'test_*.py'
go test ./...
go vet ./...
make build-all

echo "Kie API, Academy method, and model-evidence refresh complete. Review git diff, then commit the generated artifacts."
